# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userinfo',
            new_name='test',
        ),
    ]
