# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170514_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='memo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
