# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_userinfo_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='createdate',
            field=models.DateTimeField(default='2017-05-15 07:40'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='memo',
            field=models.TextField(default='hello'),
        ),
    ]
